# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: qfvfq1@gmail.com
author_name: qfvfq1
contract_name: HelloWorld
preset_name: starter
project_name: ex

